spring:
  datasource:
    continueOnError: true
    url: jdbc:h2:file:~/test666666
    username: sa
    password:
  h2:
    console:
      path: /h2
      enabled: true
  quartz:
    jdbc:
      schema: classpath:/org/schema.sql

